repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
      stages: [commit]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      stages: [commit]
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'test_venv/bin/pip3 freeze > dev_requirements.txt; git add dev_requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]