version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    container_name: db-back
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pj-network
    logging:
      driver: json-file
      options:
        max-size: 100m
volumes:
  postgres-data:
      name: postgres
networks:
  pj-network:
    name: pj-network
